### ISSUE TITLE
paint finish bug

### ISSUE THREAD

**Issue by riverbnds** [Martinii89/OrganizeMyGarageOpenSource#7]
I'm seeing an issue where a duplicate set of paint finishes that are not able to be selected are showing in the paint finish dropdown menu. I don't know what the problem could be, any help would be appreciated

https://github.com/user-attachments/assets/9299d839-d23e-4934-a59f-1c24a78c58d1

**Comment by Martinii89** [comment]
I don't play or mod the game anymore - so I won't be investigating or solving any bugs related to this plugin

**Comment by riverbnds** [comment]
ok no problem, thanks for your plugin it works great

**Comment by riverbnds** [comment]
ok no problem, thanks for your plugin it works great
